cmake_minimum_required(VERSION 3.16)
project(opencv_20_triangulacion LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenCV REQUIRED)
add_executable(opencv_20_triangulacion main.cpp)
target_include_directories(opencv_20_triangulacion PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(opencv_20_triangulacion PRIVATE ${OpenCV_LIBS})
