cmake_minimum_required(VERSION 3.16)
project(opencv_21_puente_odometria_visual LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenCV REQUIRED)
add_executable(opencv_21_puente_odometria_visual main.cpp)
target_include_directories(opencv_21_puente_odometria_visual PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(opencv_21_puente_odometria_visual PRIVATE ${OpenCV_LIBS})
