cmake_minimum_required(VERSION 3.16)
project(opencv_14_sift LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenCV REQUIRED)
add_executable(opencv_14_sift main.cpp)
target_include_directories(opencv_14_sift PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(opencv_14_sift PRIVATE ${OpenCV_LIBS})
