cmake_minimum_required(VERSION 3.16)
project(opencv_02_adquisicion LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenCV REQUIRED)
add_executable(opencv_02_adquisicion main.cpp)
target_include_directories(opencv_02_adquisicion PRIVATE ${OpenCV_INCLUDE_DIRS})
target_link_libraries(opencv_02_adquisicion PRIVATE ${OpenCV_LIBS})
